services:
  - type: web
    name: Torrentio Italian Lite
    runtime: python  
    buildCommand: pip install --no-cache-dir -r requirements.txt  
    startCommand: uvicorn app:app --host 0.0.0.0 --port 9000 --workers 1
    plan: free 
    region: frankfurt
    envVars:
      # Sets a hardcoded value
      # (DO NOT hardcode secrets in your Blueprint file!)
      - key: PORT
        value: 9000
