services:
  - type: web
    name: Torrentio Plus
    runtime: python  
    buildCommand: pip install --no-cache-dir -r requirements.txt  
    startCommand: uvicorn app:app
    plan: free 
    region: frankfurt
    envVars:
      # Sets a hardcoded value
      # (DO NOT hardcode secrets in your Blueprint file!)
      - key: PORT
        value: 9000
